In [1]:
%load_ext autotime

time: 0 ns


### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [2]:
# Import torch and other required modules
import torch
import numpy as np

time: 4.3 s


### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [3]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64
time: 31 ms


In [4]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32
time: 0 ns


### Function 2 - torch.unsqueeze() / torch.squeeze()

In [9]:
# Example 1 - squeeze
a = np.random.random((3,1,2))
print('origin:\n',a)
a = np.squeeze(a)
print('after squeeze:\n',a)

origin:
 [[[0.59619906 0.36348092]]

 [[0.7082841  0.97270847]]

 [[0.39038748 0.39780239]]]
after squeeze:
 [[0.59619906 0.36348092]
 [0.7082841  0.97270847]
 [0.39038748 0.39780239]]
time: 16 ms


In [5]:
b = torch.rand((3,1,2))
print('origin:\n',b)
b = torch.squeeze(b)
print('after squeeze:\n',b)

origin:
 tensor([[[0.3401, 0.7762]],

        [[0.8773, 0.8147]],

        [[0.3330, 0.0041]]])
after squeeze:
 tensor([[0.3401, 0.7762],
        [0.8773, 0.8147],
        [0.3330, 0.0041]])
time: 47 ms


In [9]:
# Example 2 - unseqeeze
a = np.random.random((1,2))
print('origin:\n',a)
a = np.expand_dims(a, axis=0)  # Numpy使用的是 expand_dims
print('after squeeze:\n',a)

origin:
 [[0.1688794  0.36262593]]
after squeeze:
 [[[0.1688794  0.36262593]]]
time: 15 ms


In [10]:
a = torch.rand((1,2))
print('origin:\n',a)
a = torch.unsqueeze(a, 0)
print('after squeeze:\n',a)

origin:
 tensor([[0.3942, 0.5219]])
after squeeze:
 tensor([[[0.3942, 0.5219]]])
time: 16 ms


### Function 3 - your function to illustrate

In [21]:
# Example 1 - numpy.transpose()
a = np.random.random((1,2,3))
print('origin:\n',a)
a = np.transpose(a, [2,1,0])
print('after transpose/permute:\n',a)

origin:
 [[[0.81059334 0.36158848 0.15315895]
  [0.12983558 0.2673569  0.68799659]]]
after transpose/permute:
 [[[0.81059334]
  [0.12983558]]

 [[0.36158848]
  [0.2673569 ]]

 [[0.15315895]
  [0.68799659]]]
time: 15 ms


In [24]:
# Example 2 - tensor.permute()
a = torch.rand((1,2,3))
print('origin:\n',a)
a = torch.transpose(a, (2,1,0))  # torch.transpose 只能對調 2個欄
print('after transpose/permute:\n',a)
a.permute()

origin:
 tensor([[[0.2941, 0.8085, 0.2087],
         [0.6425, 0.8145, 0.5728]]])


TypeError: transpose() received an invalid combination of arguments - got (Tensor, tuple), but expected one of:
 * (Tensor input, name dim0, name dim1)
 * (Tensor input, int dim0, int dim1)


time: 16 ms


In [25]:
# Example 2 - tensor.permute()
a = torch.rand((1,2,3))
print('origin:\n',a)
a = a.permute(2,1,0)
print('after transpose/permute:\n',a)

origin:
 tensor([[[0.1191, 0.3220, 0.0942],
         [0.9209, 0.1087, 0.2467]]])
after transpose/permute:
 tensor([[[0.1191],
         [0.9209]],

        [[0.3220],
         [0.1087]],

        [[0.0942],
         [0.2467]]])
time: 31 ms


### Function 4 - your function to illustrate

In [28]:
# Example 1 - numpy.reshape()
a = np.random.random((1,6))
print('origin:\n',a)
b= np.reshape(a, (-1,1))
print('after reshape:\n',b)

origin:
 [[0.48840465 0.27992424 0.25826041 0.78375867 0.7249948  0.29847811]]
after reshape:
 [[0.48840465]
 [0.27992424]
 [0.25826041]
 [0.78375867]
 [0.7249948 ]
 [0.29847811]]
time: 0 ns


In [30]:
# Example 2 - tensor.reshape()
a = torch.rand((1,6))
print('origin:\n',a)
b = torch.reshape(a, (-1,1))
print('after reshape:\n',b)

origin:
 tensor([[0.5255, 0.9482, 0.0315, 0.4613, 0.8423, 0.1484]])
after reshape:
 tensor([[0.5255],
        [0.9482],
        [0.0315],
        [0.4613],
        [0.8423],
        [0.1484]])
time: 16 ms
